export enum ChromeMessageTypes {
  QUEUE_STATUS = "QUEUE_STATUS",
  SEND_MESSAGE = "SEND_MESSAGE",
  SEND_POLL = "SEND_POLL",
  PAUSE_QUEUE = "PAUSE_QUEUE",
  RESUME_QUEUE = "RESUME_QUEUE",
  STOP_QUEUE = "STOP_QUEUE",
  ADD_LOG = "ADD_LOG",
}

